### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by capumia** [zuck007/cmdjudge#1]
/usr/local/bin/cmdjudge: line 86: timeout: command not found
i dont know how to fix this, can you help me
![screen shot 2016-10-24 at 9 28 25 pm](https://cloud.githubusercontent.com/assets/17354453/19649649/d586d26e-9a30-11e6-93ec-e95df56b9c50.png)

**Comment by prdpx7** [comment]
i think you haven't installed gnu coreutils on your osx machine.
may be [this](http://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x) can solve your problem
